
#### REGISTER
POST http://localhost:5141/api/auth/register
Content-Type: application/json

{
    "username": "Ogge",
    "email": "Ogge@mail.com",
    "password": "Test123!"
}

### LOGIN
POST http://localhost:5141/api/auth/login
Content-Type: application/json

{
    "username": "Ogge",
    "password": "Test123!"
}